
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# general
image: Visual Studio 2017

# version format
version: 1.1.{build}
configuration: Release

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

pull_requests:
  do_not_increment_build_number: true

before_build:
  - nuget restore

build:
  project: TumblrSharp.sln
  publish_nuget: false
  verbosity: minimal

after_build:
  - ps: >-
      nuget pack TumblrSharp.nuspec -version $env:APPVEYOR_BUILD_VERSION

      Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
    artifact: /.*\.nupkg/
    provider: NuGet
    api_key:
      secure: mtdR95zhrXrql7GZZ8wz82A1n9TF1BroFX8OAeG+sLTdwqFiOxCbrFGuevrCANWm
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
