
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.1.{build}
configuration: Release

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

before_build:
  - nuget restore

build:
  project: TumblrSharp.sln
  publish_nuget: true
  verbosity: minimal

after_build:
  - ps: >-
      nuget pack TumblrSharp\TumblrSharp.nuspec -version $env:APPVEYOR_BUILD_VERSION

      Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      
deploy:
    artifact: /.*\.nupkg/
    provider: NuGet
    api_key:
      secure: LOtfBJIPTd6epDZ6KmxB/r8QmvlXGyaBLBlYI67Q1Uk=
    on:
      branch: master                 # release from master branch only
